### PR TITLE
Added a php::mysql class and fixed / refactored some small things

### PR DESCRIPTION
**Pull request by walterheck**

### CODE REVIEW

**Comment by Seldaek** [comment]
Do you have any idea why the mysql.ini and other mysql/pdo related config files are being created empty while other extensions are loaded just fine if one uses this?

```
    php::module { ['intl', 'gd', 'mysqlnd', 'mysql', 'curl']:
        notify => Class['php::fpm::service'],
    }
```

**Comment by saz** [comment]
@walterheck Most of your pull request looks good, thanks. But still a couple of questions occur.
- What if I use php::module to install mysql module and your module at the same time? One will win, the other will produce an error. I've thought about it, too, to use per-module classes, but I think it's lacking some flexibility.
- Instead of creating one (or more - in case of mysql) config files in this module, what about using a template? What do you think?

**Comment by saz** [comment]
@Seldaek Could you please open a seperat issue and paste the lines you're doing anything with puppet-php? It's easier for me to help you.

**Comment by philsturgeon** [comment]
Not sure why @walterheck removed his fork, but these fixes should be made to this module. I got stung with `Service[apache]` being hardcoded and came here to see if anyone had fixed it, they have.

Sadly applying the patch causes errors too, so thats not a quick fix. I'm currently manually copying and pasting changes... Could you try and manually merge this @saz? 

_Edit: Scratch that, I'll send you a pull request with just the changed I've confirmed._

**Comment by walterheck** [comment]
Closing this PR as the module is inactive and we don't use this anymore.

**Pull request closed without merging**
